{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64fce443-3129-4798-a6cd-6070e6278302",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pymysql\n",
    "import pandas as pd\n",
    "from datetime import time\n",
    "\n",
    "# Function to establish a connection to the MySQL database\n",
    "def get_db_connection():\n",
    "    return pymysql.connect(\n",
    "        host='127.0.0.1',\n",
    "        user='root',\n",
    "        password='Nikil@8405',\n",
    "        database='red_bus'\n",
    "    )\n",
    "\n",
    "@st.cache_data\n",
    "def load_data(query):\n",
    "    connection = get_db_connection()\n",
    "    df = pd.read_sql(query, connection)\n",
    "    \n",
    "    # Check if Departing_Time and Reaching_Time are in timedelta format\n",
    "    if 'Departing_Time' in df.columns:\n",
    "        df['Departing_Time'] = df['Departing_Time'].apply(lambda x: str(x).split(' ')[-1][:5])  # Extract HH:MM\n",
    "    \n",
    "    if 'Reaching_Time' in df.columns:\n",
    "        df['Reaching_Time'] = df['Reaching_Time'].apply(lambda x: str(x).split(' ')[-1][:5])  # Extract HH:MM\n",
    "    \n",
    "    connection.close()\n",
    "    return df\n",
    "\n",
    "   \n",
    "# Title and description for the app\n",
    "st.title(\"Red Bus Data Explorer\")\n",
    "st.write(\"Explore and filter the data based on the following criteria:\")\n",
    "\n",
    "# Sidebar for filtering options\n",
    "st.sidebar.header(\"Search the Buses\")\n",
    "\n",
    "# Load distinct states for selection\n",
    "states_df = load_data(\"SELECT DISTINCT state FROM bus_routes\")\n",
    "states_list = states_df['state'].tolist()\n",
    "\n",
    "# Display a selectbox for state selection\n",
    "state = st.sidebar.selectbox(\"Select the State\", states_list)\n",
    "\n",
    "# Bus type selection\n",
    "bus_type = st.sidebar.selectbox(\"Select the Bus Type\", [\"All\", \"A/C\", \"Seater\", \"NON A/C\", \"Sleeper\", \"Semi Sleeper\"])\n",
    "\n",
    "# Load distinct route names based on the selected state\n",
    "if state:\n",
    "    route_name_df = load_data(f\"SELECT DISTINCT route_name FROM bus_routes WHERE state = '{state}'\")\n",
    "    route_name_list = route_name_df['route_name'].tolist()\n",
    "\n",
    "    \n",
    "    route_name = st.sidebar.selectbox(\"Select the Route Name\", route_name_list)\n",
    "\n",
    "\n",
    "# Price range filter\n",
    "price = st.sidebar.slider(\"Select the Price range\", min_value=80, max_value=5000, value=(200, 1000))\n",
    "\n",
    "\n",
    "# Departing time checkboxes\n",
    "st.sidebar.write(\"Depature Time\")\n",
    "departing_time1 = st.sidebar.checkbox(\"Before 6 AM\", value=False)\n",
    "departing_time2 = st.sidebar.checkbox(\"6 AM to 12 PM\", value=False)\n",
    "departing_time3 = st.sidebar.checkbox(\"12 PM to 6 PM\", value=False)\n",
    "departing_time4 = st.sidebar.checkbox(\"After 6 PM\", value=False)\n",
    "\n",
    "# Star rating and seats available sliders\n",
    "star_rating = st.sidebar.slider(\"Select the Star Ratings range:\", min_value=1, max_value=5, value=(1, 2))\n",
    "seats_available = st.sidebar.slider(\"Select the Seat availability:\", min_value=1, max_value=65, value=(5, 35))\n",
    "\n",
    "# Search button\n",
    "search = st.sidebar.button(\"Search\")\n",
    "\n",
    "# Build SQL Query dynamically\n",
    "if search:\n",
    "    query = \"\"\"\n",
    "    SELECT Route_Name, Route_link, Bus_Name, Bus_Type, Departing_Time, Duration, Reaching_Time, Star_Rating, Price, seats_available \n",
    "    FROM bus_routes WHERE 1=1\n",
    "    \"\"\"\n",
    "\n",
    "    # Apply bus type filter\n",
    "    if bus_type != \"All\":\n",
    "        query += f\" AND Bus_Type LIKE '%{bus_type}%'\"\n",
    "\n",
    "    # Apply route name filter\n",
    "    if route_name:\n",
    "        query += f\" AND Route_Name LIKE '%{route_name}%'\"\n",
    "\n",
    "    # Departing time filters\n",
    "    time_conditions = []\n",
    "    if departing_time1:\n",
    "        time_conditions.append(\"Departing_Time < '06:00:00'\")\n",
    "    if departing_time2:\n",
    "        time_conditions.append(\"Departing_Time BETWEEN '06:00:00' AND '12:00:00'\")\n",
    "    if departing_time3:\n",
    "        time_conditions.append(\"Departing_Time BETWEEN '12:00:00' AND '18:00:00'\")\n",
    "    if departing_time4:\n",
    "        time_conditions.append(\"Departing_Time > '18:00:00'\")\n",
    "    \n",
    "    if time_conditions:\n",
    "        query += f\" AND ({' OR '.join(time_conditions)})\"\n",
    "\n",
    "    # Apply price filter\n",
    "    query += f\" AND Price BETWEEN {price[0]} AND {price[1]}\"\n",
    "\n",
    "    # Apply star rating filter\n",
    "    query += f\" AND Star_Rating BETWEEN {star_rating[0]} AND {star_rating[1]}\"\n",
    "\n",
    "    # Apply seats available filter\n",
    "    query += f\" AND seats_available BETWEEN {seats_available[0]} AND {seats_available[1]}\"\n",
    "\n",
    "    # Load and display filtered data\n",
    "    filtered_data = load_data(query)\n",
    "    st.write(f\"Total number of buses found: {len(filtered_data)}\")\n",
    "\n",
    "    if filtered_data.empty:\n",
    "        st.write(\"No buses available based on the selected filters.\")\n",
    "    else:\n",
    "        st.dataframe(filtered_data)\n",
    "\n",
    "# Show top-rated buses based on checkbox\n",
    "if st.sidebar.checkbox(\"Show Top Rated Buses\", value=True):\n",
    "    st.sidebar.write(\"Uncheck the checkbox to view only filtered bus details.\")\n",
    "\n",
    "    top_rated_query = \"\"\"\n",
    "    SELECT Route_Name, Bus_Name, Bus_Type,Departing_Time, Star_Rating, Price\n",
    "    FROM bus_routes\n",
    "    ORDER BY Star_Rating DESC\n",
    "    LIMIT 5;\n",
    "    \"\"\"\n",
    "    top_rated_buses = load_data(top_rated_query)\n",
    "    st.markdown(\"[Visit RedBus](https://www.redbus.in)\")\n",
    "    st.subheader(\"Top 5 Rated Buses\")\n",
    "    st.table(top_rated_buses) \n",
    "    \n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
